stateDiagram-v2

    state Public {
        state start_condition_public <<choice>>
        state "started" as started_public
        state "gather members" as members_public

        [*] --> members_public
        members_public --> start_condition_public
        start_condition_public --> members_public: less than 3
        start_condition_public --> started_public: 3 or more members
        started_public --> [*]
    }

    state Private {
        state start_condition_private <<choice>>
        state "started" as started_private
        state "send invitations" as members_private

        [*] --> members_private
        members_private --> start_condition_private
        start_condition_private --> members_private: less than 3
        start_condition_private --> started_private: 3 or more members
        started_private --> [*]
    }

    [*] --> Draft
    Draft --> [*]: Remove

    state publish_campaign <<fork>>
    Draft --> publish_campaign
    publish_campaign --> Public
    publish_campaign --> Private

    state completed <<join>>
    Public --> completed
    Private --> completed
    completed --> [*]
